name: CI

on: [push]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - native_static
          - native_dyn
          - win32_static
          - win32_dyn
        include:
          - target: native_static
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
          - target: native_dyn
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
          - target: win32_static
            image_variant: f35
            lib_postfix: '64'
          - target: win32_dyn
            image_variant: f35
            lib_postfix: '64'
    env:
      HOME: /home/runner
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/kiwix/kiwix-build_ci_${{matrix.image_variant}}:36"
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: kiwix/kiwix-build/actions/dl_deps_archive@main
      with:
        target_platform: ${{ matrix.target }}
    - name: Compile
      shell: bash
      run: |
        if [[ "${{matrix.target}}" =~ .*_static ]]; then
          MESON_OPTION="-Dstatic-linkage=true"
        else
          MESON_OPTION=""
        fi
        if [[ ! "${{matrix.target}}" =~ native_.* ]]; then
          MESON_OPTION="$MESON_OPTION --cross-file $HOME/BUILD_${{matrix.target}}/meson_cross_file.txt"
        fi
        meson . build ${MESON_OPTION}
        cd build
        ninja
      env:
        PKG_CONFIG_PATH: "${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/lib/pkgconfig:${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/lib${{matrix.lib_postfix}}/pkgconfig"
        CPPFLAGS: "-I${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/include"
